# Generated by Django 3.1.4 on 2020-12-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('resumes', '0002_auto_20201229_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='is_team_resume',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='team',
        ),
        migrations.AddField(
            model_name='resume',
            name='teams',
            field=models.ManyToManyField(related_name='resumes', to='teams.Team', verbose_name='Resume owner team'),
        ),
    ]
