# Generated by Django 3.1.4 on 2020-12-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_items', '0002_auto_20201229_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ('-created_at',), 'verbose_name': 'Work experience', 'verbose_name_plural': 'Work experiences'},
        ),
    ]
