# Generated by Django 3.1.4 on 2020-12-31 05:24

import apps.resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_auto_20201230_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.resumes.models.get_img_path, verbose_name='Resume image'),
        ),
    ]
