# Generated by Django 3.1.4 on 2020-12-27 05:16

import apps.resume_items.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('languages', '__first__'),
        ('universities', '__first__'),
        ('resumes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at date')),
                ('company', models.CharField(max_length=255, verbose_name='Company / Project name')),
                ('role', models.TextField(blank=True, null=True, verbose_name='Role in company / Or short description of project')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Responsibilities description / Or Full description of project')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, default=None, help_text='Make null if "work till this moment"', null=True, verbose_name='End date')),
                ('resume_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='contenttypes.contenttype', verbose_name='Resume users/teams')),
            ],
            options={
                'verbose_name': 'Work experience',
                'verbose_name_plural': 'Work experiences',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResumeLanguage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at date')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2, verbose_name='Level')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language', verbose_name='Language')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.userresume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'ResumeLanguage',
                'verbose_name_plural': 'ResumeLanguages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at date')),
                ('gpa', models.FloatField(blank=True, default=0, null=True, verbose_name='GPA')),
                ('start_year', models.PositiveIntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=apps.resume_items.models.current_year, verbose_name='Start year')),
                ('end_year', models.PositiveIntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=apps.resume_items.models.current_year, verbose_name='End year')),
                ('faculty', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_students', to='universities.faculty', verbose_name='Faculty')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_educations', to='resumes.userresume', verbose_name='User resume education')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_students', to='universities.university', verbose_name='University')),
            ],
            options={
                'ordering': ('-uuid',),
                'abstract': False,
            },
        ),
    ]
