# Generated by Django 3.1.4 on 2020-12-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stack',
            field=models.ManyToManyField(related_name='teams', to='stacks.Stack'),
        ),
    ]
