# Generated by Django 3.1.4 on 2020-12-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_at',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
    ]
