# Generated by Django 3.1.4 on 2020-12-31 05:23

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.get_img_path, verbose_name='User image'),
        ),
    ]
